name    'sfl-ldap'
version '0.0.1'
source 'UNKNOWN'
author 'sfl'
license 'GPL 3.0'
summary 'Setup OpenLDAP client'
description 'Setup OpenLDAP client'
project_page 'None'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
