# -*- mode: ruby -*-

Vagrant::Config.run do |config|
  config.vm.box = "SFL-AUF-django1.4-cartographie"
  # config.vm.box_url = "http://mathie-vagrant-boxes.s3.amazonaws.com/debian_squeeze_32.box"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
  config.vm.host_name = "sfl.auf.cartographie"

  config.vbguest.auto_update = false
  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  # config.vm.network :hostonly, "42.42.42.42"

  # Assign this VM to a bridged network, allowing you to connect directly to a
  # network using the host's network device. This makes the VM appear as another
  # physical device on your network.
  # config.vm.network :bridged

  config.vm.forward_port 8000, 8080

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  config.vm.share_folder "cartographie", "/home/vagrant/cartographie", "../../cartographie-maison"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "default.pp"
    puppet.module_path  = "puppet-modules"
  end

  # # importer le dump pour datamaster
  # config.vm.provision :shell, :inline => "mysql -h localhost -u root datamaster < ../../mysql-dumps/datamaster.sql"
end
